version: '3.7'

services:
  app:
    container_name: pixiki-bot
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    environment:
      NODE_ENV: production
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    command: npm run start
    depends_on:
      - db
    ports:
      - "5003:5000"
    restart: unless-stopped  
  db:
    container_name: pixiki-bot-db
    image: postgres:16
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db-dev-data:/var/lib/postgresql/data  

volumes:
  db-dev-data:
  pgadmin-data:

networks:
  default: {}